# Generated by Django 2.2.2 on 2019-06-21 10:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('newhome', '0002_auto_20190619_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Book Name', max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.UUIDField(default=uuid.uuid4, help_text='generated unique id for student', primary_key=True, serialize=False, verbose_name='student Id')),
                ('student_name', models.CharField(help_text='Student Name', max_length=100, null=True)),
                ('student_branch', models.CharField(help_text='Student branch', max_length=100, null=True)),
                ('student_sem', models.CharField(help_text='Student Sem', max_length=100, null=True)),
                ('borrow_date', models.DateField(blank=True, null=True)),
                ('total_book_borrowed', models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five')], max_length=1, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='author',
            name='Aname',
        ),
        migrations.RemoveField(
            model_name='book',
            name='library',
        ),
        migrations.AddField(
            model_name='author',
            name='author_name',
            field=models.CharField(help_text='Name of Author', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='total_book_written',
            field=models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='generated unique id for book', primary_key=True, serialize=False, verbose_name='Book Id'),
        ),
        migrations.DeleteModel(
            name='Library',
        ),
        migrations.AddField(
            model_name='student',
            name='book_name',
            field=models.ForeignKey(help_text='Book Name', null=True, on_delete=django.db.models.deletion.SET_NULL, to='newhome.Book'),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='genre of book', to='newhome.Genre'),
        ),
    ]
